development: &defaults
  client_id: UPDATE
  client_secret: UPDATE
  callback: 'http://localhost:3010/connect/facebook'
  scope: user_birthday, user_location, user_website, email

test:
  <<: *defaults

production:
  <<: *defaults
