development: &defaults
  client_id: UPDATE.apps.googleusercontent.com
  client_secret: UPDATE
  issuer: https://accounts.google.com
  redirect_uri: http://localhost:3010/connect/google

test:
  <<: *defaults

production:
  <<: *defaults
  redirect_uri: https://connect-op.herokuapp.com/connect/google
